# Generated by Django 5.2.6 on 2025-10-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestor', '0003_alter_alumno_fecha_ingreso'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextendido',
            name='alumno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGestor.alumno'),
        ),
    ]
