# Generated by Django 5.2.6 on 2025-10-13 18:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='biografia',
            field=ckeditor.fields.RichTextField(default='Sin biografía'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
    ]
