# Generated by Django 5.2.6 on 2025-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestor', '0002_alumno_biografia_alumno_fecha_ingreso_alumno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
